# Generated by Django 2.2.17 on 2020-12-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_education_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.CharField(default=99, max_length=100, verbose_name='会社'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='occupation',
            field=models.CharField(max_length=100, verbose_name='職種'),
        ),
    ]
